MMDb/MMDb/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('films/', include("filmsList.urls"))
]

MMDb/filmsList/urls.py
from django.urls import path
from . import views

app_name = "filmsList"
urlpatterns = [
     path("", views.index, name="index"),
     path("add", views.addFilm, name="add")
]

MMDb/filmsList/models.py
from django.db import models

# Create your models here.

MMDb/filmsList/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django import forms

from datetime import datetime
import csv

class AddNewForm(forms.Form):
    name = forms.CharField(label="Name", widget=forms.TextInput(attrs={'class': 'input_area', 'placeholder': 'name'}))
    language = forms.CharField(label="language", widget=forms.TextInput(attrs={'class': 'input_area', 'placeholder':'language'}))
    year = forms.IntegerField(label="Year",
                              widget=forms.TextInput(attrs={'class': 'input_area' , 'placeholder':'year'}),
                              max_value=3000
                            )
    rate = forms.FloatField(label="Rating" , widget=forms.TextInput(attrs={'class': 'input_area' , 'placeholder':'rate'}))
    type = forms.CharField(label="Type" , widget=forms.TextInput(attrs={'class': 'input_area' , 'placeholder':'type'}))



def index(request):

    with open('films.csv', newline='') as filmscsv:
        films_dict = csv.DictReader(filmscsv)
        date = datetime.now()
        return render(request, "filmsList/index.html",{
            'year':date.year,
            'month':date.month,
            'day':date.day,
            'films':films_dict,
        })
    
def addFilm(request):

    if request.method == "POST":
        form = AddNewForm(request.POST)

        if form.is_valid():
            fieldNames = [
                'name',
                'language',
                'year',
                'rating',
                'type'
            ]
            with open('films.csv', 'a' ,newline='\n') as filmscsv:
                write = csv.DictWriter(filmscsv, fieldnames=fieldNames)
                write.writerow({
                    'name': form.cleaned_data['name'],
                    'language': form.cleaned_data['language'],
                    'year': form.cleaned_data['year'],
                    'rating': form.cleaned_data['rate'],
                    'type': form.cleaned_data['type']
                })

    return render(request, "filmsList/addFilm.html",{
        'form': AddNewForm()
    })

MMDb/filmsList/templates/filmsList/addFilm.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Add Film</title>
    <link rel="stylesheet" href="{% static 'add.css' %}">
</head>
<body>
    <form action="{% url 'filmsList:add' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="submit-btn">
    </form>
    <div class="links">
        <a href="{% url 'filmsList:index' %}">view films list</a>
    </div>
</body>
</html>

MMDb/filmsList/templates/filmsList/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Films List</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <div class="container">
        <div class="date">{{ day }} / {{ month }} / {{ year }}</div>
        <table>
            <thead>
                <th>Name</th>
                <th>Language</th>
                <th>Year</th>
                <th>Rating</th>
                <th>Type</th>
            </thead>
            <tbody>
                {% for row in films %}
                <tr>
                    <td>{{ row.name }}</td>
                    <td>{{ row.language }}</td>
                    <td>{{ row.year }}</td>
                    <td>{{ row.rating }}</td>
                    <td>{{ row.type }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>